# SQL Server ????
db.url=jdbc:sqlserver://localhost:1433;databaseName=StudentDB;encrypt=true;trustServerCertificate=true
db.user=sa
db.password=898087902
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver